# Generated by Django 5.2.4 on 2025-07-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
